apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if eq .Values.image.tag "latest"}}
          image: "{{ .Values.image.name }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          {{- else}}
          image: "{{ .Values.image.devRepo }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PUBSUB_TOPIC
            value: sample-jobs
          - name: PUBSUB_SUB_ID
            value: sample-workers
          - name: SAMPLE_SERVICE_BASE_URL
            value: {{.Values.sample.service.baseUrl}}
          - name: SAMPLE_SERVICE_PATH
            value: {{.Values.sample.service.path}}
          - name: VERBOSE
            value: {{.Values.verbose | quote }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
