env: sandbox

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "200m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 500
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

verbose: true

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: rm-ras-sandbox
  topic: sample-jobs
  subscription: sample-workers