env: sandbox
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "256Mi"

sample:
  service:
    baseUrl: "http://localhost:8080"
    path: "/samples"

verbose: true
